/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function p(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};
function t(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var u=t(this);function v(a,b){if(b)a:{var e=u;a=a.split(".");for(var f=0;f<a.length-1;f++){var h=a[f];if(!(h in e))break a;e=e[h]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&null!=b&&r(e,a,{configurable:!0,writable:!0,value:b})}}
v("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e(f+(l||"")+"_"+h++,l)}function e(l,c){this.g=l;r(this,"description",{configurable:!0,writable:!0,value:c})}if(a)return a;e.prototype.toString=function(){return this.g};var f="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",h=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<b.length;e++){var f=u[b[e]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&r(f.prototype,a,{configurable:!0,writable:!0,value:function(){return w(p(this))}})}return a});function w(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function x(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:p(a)}}function y(){this.j=!1;this.g=null;this.l=void 0;this.h=1;this.o=0;this.i=null}function z(a){if(a.j)throw new TypeError("Generator is already running");a.j=!0}y.prototype.m=function(a){this.l=a};function D(a,b){a.i={F:b,isException:!0};a.h=a.o}y.prototype.return=function(a){this.i={return:a};this.h=this.o};function E(a,b,e){a.h=e;return{value:b}}function F(a){this.g=new y;this.h=a}
function G(a,b){z(a.g);var e=a.g.g;if(e)return H(a,"return"in e?e["return"]:function(f){return{value:f,done:!0}},b,a.g.return);a.g.return(b);return I(a)}function H(a,b,e,f){try{var h=b.call(a.g.g,e);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.g.j=!1,h;var l=h.value}catch(c){return a.g.g=null,D(a.g,c),I(a)}a.g.g=null;f.call(a.g,l);return I(a)}
function I(a){for(;a.g.h;)try{var b=a.h(a.g);if(b)return a.g.j=!1,{value:b.value,done:!1}}catch(e){a.g.l=void 0,D(a.g,e)}a.g.j=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.isException)throw b.F;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function J(a){this.next=function(b){z(a.g);a.g.g?b=H(a,a.g.g.next,b,a.g.m):(a.g.m(b),b=I(a));return b};this.throw=function(b){z(a.g);a.g.g?b=H(a,a.g.g["throw"],b,a.g.m):(D(a.g,b),b=I(a));return b};this.return=function(b){return G(a,b)};this[Symbol.iterator]=function(){return this}}function K(a){function b(f){return a.next(f)}function e(f){return a.throw(f)}return new Promise(function(f,h){function l(c){c.done?f(c.value):Promise.resolve(c.value).then(b,e).then(l,h)}l(a.next())})}
function L(a){return K(new J(new F(a)))}
v("Promise",function(a){function b(c){this.h=0;this.i=void 0;this.g=[];this.o=!1;var d=this.j();try{c(d.resolve,d.reject)}catch(g){d.reject(g)}}function e(){this.g=null}function f(c){return c instanceof b?c:new b(function(d){d(c)})}if(a)return a;e.prototype.h=function(c){if(null==this.g){this.g=[];var d=this;this.i(function(){d.l()})}this.g.push(c)};var h=u.setTimeout;e.prototype.i=function(c){h(c,0)};e.prototype.l=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var d=0;d<c.length;++d){var g=
c[d];c[d]=null;try{g()}catch(k){this.j(k)}}}this.g=null};e.prototype.j=function(c){this.i(function(){throw c;})};b.prototype.j=function(){function c(k){return function(m){g||(g=!0,k.call(d,m))}}var d=this,g=!1;return{resolve:c(this.A),reject:c(this.l)}};b.prototype.A=function(c){if(c===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.C(c);else{a:switch(typeof c){case "object":var d=null!=c;break a;case "function":d=!0;break a;default:d=!1}d?this.v(c):this.m(c)}};
b.prototype.v=function(c){var d=void 0;try{d=c.then}catch(g){this.l(g);return}"function"==typeof d?this.D(d,c):this.m(c)};b.prototype.l=function(c){this.u(2,c)};b.prototype.m=function(c){this.u(1,c)};b.prototype.u=function(c,d){if(0!=this.h)throw Error("Cannot settle("+c+", "+d+"): Promise already settled in state"+this.h);this.h=c;this.i=d;2===this.h&&this.B();this.G()};b.prototype.B=function(){var c=this;h(function(){if(c.H()){var d=u.console;"undefined"!==typeof d&&d.error(c.i)}},1)};b.prototype.H=
function(){if(this.o)return!1;var c=u.CustomEvent,d=u.Event,g=u.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):"function"===typeof d?c=new d("unhandledrejection",{cancelable:!0}):(c=u.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.i;return g(c)};b.prototype.G=function(){if(null!=this.g){for(var c=0;c<this.g.length;++c)l.h(this.g[c]);this.g=null}};var l=new e;b.prototype.C=
function(c){var d=this.j();c.s(d.resolve,d.reject)};b.prototype.D=function(c,d){var g=this.j();try{c.call(d,g.resolve,g.reject)}catch(k){g.reject(k)}};b.prototype.then=function(c,d){function g(n,q){return"function"==typeof n?function(A){try{k(n(A))}catch(B){m(B)}}:q}var k,m,C=new b(function(n,q){k=n;m=q});this.s(g(c,k),g(d,m));return C};b.prototype.catch=function(c){return this.then(void 0,c)};b.prototype.s=function(c,d){function g(){switch(k.h){case 1:c(k.i);break;case 2:d(k.i);break;default:throw Error("Unexpected state: "+
k.h);}}var k=this;null==this.g?l.h(g):this.g.push(g);this.o=!0};b.resolve=f;b.reject=function(c){return new b(function(d,g){g(c)})};b.race=function(c){return new b(function(d,g){for(var k=x(c),m=k.next();!m.done;m=k.next())f(m.value).s(d,g)})};b.all=function(c){var d=x(c),g=d.next();return g.done?f([]):new b(function(k,m){function C(A){return function(B){n[A]=B;q--;0==q&&k(n)}}var n=[],q=0;do n.push(void 0),q++,f(g.value).s(C(n.length-1),m),g=d.next();while(!g.done)})};return b});function M(){}var N;function O(a,b){return L(function(e){return e.return((new Promise(function(f){chrome.storage.sync.get([a],f)})).then(function(f){return"undefined"===typeof f[a]?b:f[a]}))})}function P(){return L(function(a){return a.return(O("defaultRegion","US"))})}function Q(){return L(function(a){return a.return(O("enableLinkification",!0))})};function R(){N||(N=new M);this.g=document.getElementsByClassName("voiceDefaultRegion")[0];this.h=document.getElementsByClassName("voiceEnableLinkification")[0]};(function(){var a=new R,b,e;L(function(f){if(1==f.h)return E(f,P(),2);if(3!=f.h)return b=f.l,E(f,Q(),3);e=f.l;a.g.value=b;a.h.checked=e;a.g.addEventListener("change",function(){var h={};h.defaultRegion=a.g.value;chrome.storage.sync.set(h)});a.h.addEventListener("change",function(){var h={};h.enableLinkification=a.h.checked;chrome.storage.sync.set(h)});f.h=0})})();
