$background = rgb(0D0C13)
$foreground = rgb(F1ECEC)
$color0 = rgb(0D0C13)
$color1 = rgb(2F314A)
$color2 = rgb(31506C)
$color3 = rgb(325B79)
$color4 = rgb(886E77)
$color5 = rgb(66798C)
$color6 = rgb(A29796)
$color7 = rgb(E3DCDB)
$color8 = rgb(9F9A99)
$color9 = rgb(3F4263)
$color10 = rgb(416A90)
$color11 = rgb(4279A1)
$color12 = rgb(B5929F)
$color13 = rgb(88A1BA)
$color14 = rgb(D8C9C8)
$color15 = rgb(E3DCDB)
