[pyprland]

plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "toggle_special"
]


[scratchpads.term]
animation = "fromBottom"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "50% 50%"

[scratchpads.ranger]
animation = "fromBottom"
command = "alacritty -e ranger"
class = "alacritty-dropdown"
size = "50% 50%"
