/* Copyright 2010 Google Inc. All Rights Reserved. http://tools.google.com/dlpage/gaoptout/intl/en/eula_text.html */ (function(){var f=function(a){return a.raw=a},g=function(a,c){a.raw=c;return a},h=function(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,l=function(a,c){function b(){}b.prototype=c.prototype;a.s=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.o=function(d,e,na){for(var E=Array(arguments.length-2),r=2;r<arguments.length;r++)E[r-2]=arguments[r];return c.prototype[e].apply(d,E)}},m=function(a){return a};function n(a,c){if(Error.captureStackTrace)Error.captureStackTrace(this,n);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));void 0!==c&&(this.cause=c)}l(n,Error);n.prototype.name="CustomError";function p(a,c){a=a.split("%s");for(var b="",d=a.length-1,e=0;e<d;e++)b+=a[e]+(e<c.length?c[e]:"%s");n.call(this,b+a[d])}l(p,n);p.prototype.name="AssertionError";var q=function(a,c){throw new p("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var t;var v=function(a,c){if(c!==u)throw Error("TrustedResourceUrl is not meant to be built directly");this.g=a};v.prototype.toString=function(){return this.g+""};
var w=function(a){if(a instanceof v&&a.constructor===v)return a.g;var c=typeof a;q("expected object of type TrustedResourceUrl, got '%s' of type %s",a,"object"!=c?c:a?Array.isArray(a)?"array":c:"null");return"type_error:TrustedResourceUrl"},u={},x=function(a){if(void 0===t){var c=null;var b=k.trustedTypes;if(b&&b.createPolicy)try{c=b.createPolicy("goog#html",{createHTML:m,createScript:m,createScriptURL:m})}catch(d){k.console&&k.console.error(d.message)}t=c}a=(c=t)?c.createScriptURL(a):a;return new v(a,
u)};/*

 SPDX-License-Identifier: Apache-2.0
*/
var y=f([""]),aa=g(["\x00"],["\\0"]),ba=g(["\n"],["\\n"]),ca=g(["\x00"],["\\u0000"]),da=f([""]),ea=g(["\x00"],["\\0"]),fa=g(["\n"],["\\n"]),ha=g(["\x00"],["\\u0000"]);function z(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function A(a){return-1===a.toString().indexOf("`")}var B=A(function(a){return a(y)})||A(function(a){return a(aa)})||A(function(a){return a(ba)})||A(function(a){return a(ca)}),ia=z(da)&&z(ea)&&z(fa)&&z(ha);var C={};var D=function(a){if(C!==C)throw Error("Bad secret");this.m=a};D.prototype.toString=function(){return this.m};new D("about:blank");new D("about:invalid#zClosurez");var F=function(a){this.h=a};function G(a){return new F(function(c){return c.substr(0,a.length+1).toLowerCase()===a+":"})}var ja=new F(function(a){return 0===a.indexOf("chrome-extension://")||0===a.indexOf("moz-extension://")||0===a.indexOf("ms-browser-extension://")}),ka=[G("data"),G("http"),G("https"),G("mailto"),G("ftp"),new F(function(a){return/^[^:]*([/?#]|$)/.test(a)})],H=[],I=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};-1===H.indexOf(I)&&H.push(I);var J={},K=function(){if(J!==J)throw Error("SafeStyle is not meant to be built directly");this.l=""};K.prototype.toString=function(){return this.l.toString()};new K;var L={},M=function(){if(L!==L)throw Error("SafeStyleSheet is not meant to be built directly");this.j=""};M.prototype.toString=function(){return this.j.toString()};new M;var N={},O=function(){var a=k.trustedTypes&&k.trustedTypes.emptyHTML||"";if(N!==N)throw Error("SafeHtml is not meant to be built directly");this.i=a};O.prototype.toString=function(){return this.i.toString()};new O;var la=f(["gaoptout_signal.js"]);document.documentElement.setAttribute("data-google-analytics-opt-out","");
var P=document.createElement("script"),Q,ma=function(a){var c=h.apply(1,arguments);if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!B&&a===a.raw||!(B&&!ia||z(a))||c.length+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");if(0===
c.length)return x(a[0]);var b=a[0].toLowerCase();if(/^data:/.test(b))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(b)||/^\/\//.test(b)){var d=b.indexOf("//")+2;var e=b.indexOf("/",d);if(e<=d)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");d=b.substring(d,e);if(!/^[0-9a-z.:-]+$/i.test(d))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(d))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(d))throw Error("The top-level domain must start with a letter.");d=!0}else d=!1;if(!d)if(/^\//.test(b))if("/"===b||1<b.length&&"/"!==b[1]&&"\\"!==b[1])d=!0;else throw Error("The path start in the url is invalid.");else d=!1;if(!(d=d||RegExp("^[^:\\s\\\\/]+/").test(b)))if(/^about:blank/.test(b)){if("about:blank"!==b&&!/^about:blank#/.test(b))throw Error("The about url is invalid.");d=!0}else d=!1;if(!d)throw Error("Trying to interpolate expressions in an unsupported url format.");
b=a[0];for(d=0;d<c.length;d++)b+=encodeURIComponent(c[d])+a[d+1];return x(b)}(la),R=chrome.runtime.getURL(w(ma).toString()),S;a:{var T=[ja];T=void 0===T?ka:T;if(R instanceof D)S=R;else{for(var U=0;U<T.length;++U){var V=T[U];if(V instanceof F&&V.h(R)){S=new D(R);break a}}S=void 0}}if(!S)throw Error('"'+R+'" is not an extension URL.');Q=x(R);P.src=w(Q);var W,X,Y,Z=null==(Y=(X=(P.ownerDocument&&P.ownerDocument.defaultView||window).document).querySelector)?void 0:Y.call(X,"script[nonce]");
(W=Z?Z.nonce||Z.getAttribute("nonce")||"":"")&&P.setAttribute("nonce",W);document.documentElement.insertBefore(P,document.documentElement.firstChild);document.documentElement.removeChild(P);})()
